// react_attempt/src/components/solve_button.jsx
function SolveButton() {
    function call_solver() {
        fetch("/solve", {
            method: "POST",
            headers: {
                "Content-Type": "application/json",
            },
            body: null, // data can be `string` or {object}!
        })
            .then((response) => response.json())
            .then((data) => console.log(data))
    }

    return <button onClick={call_solver}>Solve</button>
}

export default SolveButton

// frontend/src/lib/SolveButton.svelte
<script lang="ts">
    import { grid } from "./grid_store"

    function process_result(data) {
        if (data.status == 1) {
        } else {
            grid.set(data.grid)
        }
    }

    function callBackend() {
        fetch("/solve", {
            method: "POST",
            headers: {
                "Content-Type": "application/json",
            },
            body: JSON.stringify({ grid: $grid }),
        })
            .then((res) => res.json())
            .then((data) => process_result(data))
    }
</script>

<main>
    <button on:click={callBackend}> Solve </button>
</main>

<style>
    button {
        width: 200px;
        font-size: 30px;
    }
</style>
